import type { CivilizationPreset } from './types'

export const byzantineMacedonian: CivilizationPreset = {
  id: 'byzantine-macedonian',
  cityName: 'Порфирополис',
  rulerTitle: 'Стратег фемы',
  resources: { silver: 'Номисмы', food: 'Зерно', wood: 'Древесина', stone: 'Камень' },
  buildings: {
    road: 'Месса',
    house: 'Инсула',
    farm: 'Проастий',
    lumberCamp: 'Лесной двор',
    quarry: 'Каменоломня',
    granary: 'Зерновой фонд',
    market: 'Агора',
    smithy: 'Эргастирий',
    barracks: 'Казармы тагмы',
    watchtower: 'Фриктория',
    wall: 'Феодосиева стена',
    townHall: 'Дворец стратега',
  },
  buildingDetails: {
    road: { role: 'Городская улица', effect: 'Связывает кварталы и ворота' },
    house: { role: 'Жильё горожан', effect: 'Отдельный дом с хозяйственным двором' },
    farm: { role: 'Земледельческий двор', effect: '+14 зерна в день' },
    lumberCamp: { role: 'Заготовка древесины', effect: '+8 древесины в день' },
    quarry: { role: 'Добыча камня', effect: 'Открытый карьер с подъёмным краном' },
    granary: { role: 'Городские амбары', effect: 'Главная цель налётчиков при прорыве' },
    market: { role: 'Торговая площадь', effect: 'Аркады, лавки и городской фонтан' },
    smithy: { role: 'Оружейная мастерская', effect: 'Горн, наковальня и высокая труба' },
    barracks: { role: 'Казармы тагмы', effect: 'Двор для сбора городского войска' },
    watchtower: { role: 'Сторожевая башня', effect: 'Башня крепостного периметра' },
    wall: { role: 'Крепостной периметр', effect: 'Одна соединяемая секция стены' },
    townHall: { role: 'Центр княжества', effect: 'Неразбираемый дворец управления' },
  },
  units: { militia: 'Городское ополчение', retinue: 'Тагма', raider: 'Налётчики' },
  crises: {
    famine: { title: 'Голод в посаде', action: 'Закупить зерно', cost: '24 номисмы', alternative: 'Ввести пайки', alternativeCost: '−7 порядка' },
    rebellion: { title: 'Бунт городских демов', action: 'Даровать уступки', cost: '18 номисм · −3 легитимности', alternative: 'Вывести тагму', alternativeCost: '−3 жителя · −7 легитимности' },
    coup: { title: 'Заговор знати', action: 'Принять клятвы', cost: '28 номисм · −2 порядка', alternative: 'Арестовать заговорщиков', alternativeCost: '−8 порядка' },
  },
  threats: ['Сельджукский бейлик', 'Славянский союз', 'Арабский эмират', 'Персидская держава'],
  palette: {
    porphyry: 0x351a46,
    gold: 0xd3aa55,
    marble: 0xd8cfb8,
    brick: 0x9b4c36,
    roof: 0x8a392e,
    water: 0x173d55,
    olive: 0x667341,
    danger: 0xb84e52,
  },
}
